version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    ports:
      - "1433:1433"  
    environment:
      - ACCEPT_EULA=Y  
      - SA_PASSWORD=YourStrongPassword123! 
      - MSSQL_PID=Express  
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql  

volumes:
  sqlserver_data:






